### ISSUE TITLE
missing quality array

### ISSUE THREAD

**Issue by panaC** [HadrienGardeur/web-speech-recommended-voices#45]
https://github.com/HadrienGardeur/web-speech-recommended-voices/blob/c4f1989c97a458c1dc1c29b8699c390095de211d/json/gl.json#L10

**Comment by HadrienGardeur** [comment]
I'll add it later today but keep in mind that in some cases, I might not be able to document the quality of a voice. 
When that's the case, these voices should be listed lower than the other one, but before voiced that are not present in these JSON files.

That's not the issue here, I mistakenly skipped these voices when iterating through all files to add these quality properties.
